apiVersion: apps/v1 
kind: Deployment
metadata:
  name: regapp-deployment
  namespace: argocod
  labels: 
     app: regapp

spec:
  replicas: 2 
  selector:
    matchLabels:
      app: regapp

  template:
    metadata:
      labels:
        app: regapp
    spec:
      containers:
      - name: regapp
        image: 483216680875.dkr.ecr.us-east-1.amazonaws.com/frontend:6
        imagePullPolicy: Always
        ports:
        - containerPort: 3000
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1

---
apiVersion: v1
kind: Service
metadata:
  name: regapp-service
  namespace: argocd
  labels:
    app: regapp 
spec:
  selector:
    app: regapp 

  ports:
    - port: 3000
      targetPort: 3000

  type: LoadBalancer
